### PR TITLE
Enable paused

### PR DESCRIPTION
**Pull request by grndctrl**
#4 

Better approach than my previous suggested PR. 
I basicly just copied @bjornstar's [use-cannon PR](https://github.com/pmndrs/use-cannon/pull/342) and applied it to make it work for use-p2.

- BREAKING: step renamed to stepSize (default: 1 / 60)
- NEW: maxSubSteps (default: 10)
- NEW: isPaused 
- timeSinceLastCall not tracked in worker
- prefer FC to PropsWithChildren
- REMOVED: type DefaultContactMaterial
- MISSING: isPaused demo

### CODE REVIEW

**Review by joergjaeckel — CHANGES_REQUESTED** [review]
Hi, thank you for your effort! Sadly there are a lot of reformatting changes what shouldn't be part part of this PR. If we need to do so, lets make another PR.

**Comment by grndctrl** [comment]
Mind you, the same changes are all in the same PR over at use-cannon too though. 

EDIT: Ah my bad, I think I misunderstood and you might be referring to all the changes that happened while I ran: `npm run prettier-fix`.

**Comment by joergjaeckel** [comment]
Yes that should be the reason. Thats not a problem at all but I cant review and understand the changes while I need to search them between all the reformattings 😅 Is it possible to correct this?

For context: I copied over the prettier config from the cannon repo but never executed it

**Comment by joergjaeckel** [comment]
I pushed a prettier-fixed commit, now if you merge the conflicts what remains should be your relevant changes.

**Comment by grndctrl** [comment]
Ok I merged your changes, also removed a big comment block I forgot to delete while testing.

**Review by joergjaeckel — APPROVED** [review]
catching up with pmdrs/use-cannon#add-ispaused-property-22-02-12

**Pull request merged**
